#!/usr/bin/env python3

"""
Tag Extractor - Extracts Steam reviews grouped by genre tags and country.

Builds on steam_extractor.py: uses a local Steam catalog (generated by
steamspy_catalog_fetcher.py) to discover app IDs by user tag, then
calls the Steam API to collect reviews and enriches each review with the
author's country via GetPlayerSummaries.

Output schema: app_id | app_name | user_id | country_code | language |
               review_text | voted_up | tag | date_created

Usage:
    # First, build the local catalog (once):
    python3 steamspy_catalog_fetcher.py

    # Then extract reviews:
    python3 tag_extractor.py --tags Action FPS --countries BR US \
        --start 01/01/2023 --end 31/12/2023 \
        --api-key YOUR_KEY
"""

import argparse
import json
import logging
import os
import time
from dataclasses import dataclass
from datetime import datetime, date, timezone
from pathlib import Path

import pandas as pd
import requests

from steam_extractor.reviews_fetcher import (
    fetch_reviews_with_metadata,
    parse_date,
    save_manifest,
    software_metadata,
)

log = logging.getLogger(__name__)


def setup_logging() -> str:
    """Configures logging to console and a timestamped file under ./logs/."""
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file  = log_dir / f"extraction_{timestamp}.log"

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%d/%m/%Y %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, encoding="utf-8"),
            logging.StreamHandler(),
        ],
    )
    return str(log_file)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_DB         = "steamspy_catalog.json"
PLAYER_SUMMARY_URL = "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/"
GAME_DELAY         = 1.5
PROFILE_DELAY      = 0.5
BATCH_SIZE         = 100


@dataclass
class CountryFetchResult:
    country_map: dict[str, str]
    requested_users: int
    returned_profiles: int
    country_available: int
    failed_batches: int
    failed_users: int

    def to_metadata(self) -> dict:
        return {
            "unique_authors": self.requested_users,
            "profiles_returned": self.returned_profiles,
            "country_available": self.country_available,
            "country_unavailable": (
                self.requested_users - self.country_available - self.failed_users
            ),
            "failed_batches": self.failed_batches,
            "failed_users": self.failed_users,
            "complete": self.failed_batches == 0,
        }


# ---------------------------------------------------------------------------
# Local catalog helpers
# ---------------------------------------------------------------------------

def load_catalog_with_metadata(db_path: str) -> tuple[dict, dict]:
    """Loads games and metadata from a local SteamSpy catalog."""
    path = Path(db_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Steam catalog not found at '{db_path}'.\n"
            f"Run first: python3 steamspy_catalog_fetcher.py"
        )

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    games = data.get("games", {})
    meta  = data.get("metadata", {})
    log.info(f"Catalog loaded: {len(games):,} games from '{db_path}' (downloaded: {meta.get('downloaded_at', 'unknown')})")
    return games, meta


def load_catalog(db_path: str) -> dict:
    """Backward-compatible helper returning only games from the catalog."""
    games, _metadata = load_catalog_with_metadata(db_path)
    return games


def get_appids_by_tags(
    tags: list[str],
    games: dict,
    min_reviews: int = 0,
) -> list[dict]:
    """
    Filters the local SteamSpy catalog by multiple user tags (AND logic)
    and minimum review count. A game must have ALL specified tags to be included.
    Results are sorted by total reviews descending (most reviewed first).

    Args:
        tags:        list of user tag names (e.g. ['FPS', 'Multiplayer'])
        games:       dict loaded from steamspy_catalog.json
        min_reviews: minimum total reviews (positive + negative, default: 0)

    Returns:
        List of dicts with keys: appid, name — sorted by review count desc.
    """
    tags_lower = [t.lower() for t in tags]
    log.info(f"Filtering for tags: {tags} (AND, min reviews: {min_reviews:,})")
    filtered = []

    for appid, info in games.items():
        game_tags = [t.lower() for t in info.get("tags", {}).keys()]
        total     = (info.get("positive") or 0) + (info.get("negative") or 0)

        if all(t in game_tags for t in tags_lower) and total >= min_reviews:
            filtered.append({
                "appid":   appid,
                "name":    info.get("name", "Unknown"),
                "reviews": total,
            })

    filtered.sort(key=lambda g: g["reviews"], reverse=True)
    log.info(f"Found {len(filtered)} games matching all tags with >= {min_reviews:,} reviews")
    return filtered


# ---------------------------------------------------------------------------
# Player profile enrichment
# ---------------------------------------------------------------------------

def fetch_country_codes_with_metadata(
    user_ids: list[str], api_key: str
) -> CountryFetchResult:
    """
    Fetches country_code for a list of Steam user IDs via GetPlayerSummaries.
    Processes up to 100 IDs per API call.

    Returns dict mapping steamid → country_code (empty string if unavailable).
    """
    country_map: dict[str, str] = {}
    returned_profiles = 0
    failed_batches = 0
    failed_users = 0
    batches = [user_ids[i:i + BATCH_SIZE] for i in range(0, len(user_ids), BATCH_SIZE)]

    log.info(f"Fetching player profiles: {len(user_ids):,} users in {len(batches)} batches")

    for i, batch in enumerate(batches, start=1):
        max_retries = 3
        batch_succeeded = False
        for attempt in range(max_retries):
            try:
                r = requests.get(
                    PLAYER_SUMMARY_URL,
                    params={"key": api_key, "steamids": ",".join(batch)},
                    timeout=30
                )
                r.raise_for_status()
                players = r.json().get("response", {}).get("players", [])
                returned_profiles += len(players)
                for player in players:
                    steamid = player.get("steamid", "")
                    country = player.get("loccountrycode", "")
                    country_map[steamid] = country.upper() if country else ""
                batch_succeeded = True
                break
            except requests.exceptions.HTTPError as e:
                status = e.response.status_code if e.response is not None else "?"
                if status == 429:
                    wait = 30 * (attempt + 1)
                    log.warning(f"Rate limited on batch {i} (attempt {attempt+1}/{max_retries}), waiting {wait}s...")
                    time.sleep(wait)
                else:
                    log.warning(f"HTTP {status} error on batch {i} (attempt {attempt+1}/{max_retries})")
                    break
            except Exception as e:
                log.warning(f"Error on batch {i}: {type(e).__name__} (attempt {attempt+1}/{max_retries})")
                break

        if not batch_succeeded:
            failed_batches += 1
            failed_users += len(batch)

        if i % 10 == 0:
            log.info(f"Profile batch {i}/{len(batches)} done")

        time.sleep(PROFILE_DELAY)

    filled = sum(1 for v in country_map.values() if v)
    total  = len(user_ids)
    if total:
        log.info(f"country_code found for {filled:,} / {total:,} users ({filled/total*100:.1f}%)")

    return CountryFetchResult(
        country_map=country_map,
        requested_users=len(user_ids),
        returned_profiles=returned_profiles,
        country_available=filled,
        failed_batches=failed_batches,
        failed_users=failed_users,
    )


def fetch_country_codes(user_ids: list[str], api_key: str) -> dict[str, str]:
    """Backward-compatible wrapper returning only the country mapping."""
    return fetch_country_codes_with_metadata(user_ids, api_key).country_map


# ---------------------------------------------------------------------------
# Core extraction pipeline
# ---------------------------------------------------------------------------

def extract_reviews_by_tags(
    tags: list[str],
    countries: list[str],
    start_date: date,
    end_date: date,
    api_key: str,
    db_path: str = DEFAULT_DB,
    max_games_per_tag: int = 10,
    min_reviews: int = 0,
    appids: list[str] | None = None,
    passes: int = 1,
    game_delay: float = GAME_DELAY,
) -> pd.DataFrame:
    """
    Full pipeline:
        1. Local catalog → app IDs per tag
        2. Steam API     → reviews per app
        3. GetPlayerSummaries → country_code per user (batched)
        4. Filter by country (if --countries specified)
        5. Return structured DataFrame

    Output columns:
        app_id, app_name, recommendation_id, user_id, country_code, language,
        review_text, voted_up, tag, date_created
    """
    catalog, catalog_metadata = load_catalog_with_metadata(db_path)
    all_rows        = []
    game_metadata: list[dict] = []
    seen_appids: set[str] = set()
    countries_upper = [c.upper() for c in countries]

    def build_metadata(country_metadata: dict | None = None) -> dict:
        games_complete = bool(game_metadata) and all(
            game["complete"] for game in game_metadata
        )
        country_complete = (
            country_metadata is None or country_metadata.get("complete", False)
        )
        return {
            "schema_version": 1,
            "created_at": datetime.now(tz=timezone.utc).isoformat(),
            "software": software_metadata(),
            "query": {
                "tags": tags,
                "appids": [str(appid) for appid in appids] if appids else None,
                "countries": countries_upper,
                "language": "all",
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat(),
                "passes_requested": passes,
                "selection_mode": "explicit_appids" if appids else "tag_top_reviews",
                "max_games": max_games_per_tag,
                "min_reviews": min_reviews,
                "steam_filter": "recent",
                "offtopic_included": False,
            },
            "catalog": {**catalog_metadata, "path": db_path},
            "games": game_metadata,
            "country_enrichment": country_metadata,
            "dataset_complete": games_complete and country_complete,
        }

    # ------------------------------------------------------------------
    # Steps 1 & 2: discover games and collect reviews
    # ------------------------------------------------------------------
    tags_label = " & ".join(tags)

    if not appids:
        games_list = get_appids_by_tags(tags, catalog, min_reviews=min_reviews)
        games_list = games_list[:max_games_per_tag]
    else:
        games_list = []

    if not games_list and not appids:
        log.warning(f"No games found matching all tags: {tags}")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    tag = tags_label

    # Handle --appids: build games_list from explicit appids if provided
    if appids:
        games_list = [
            {
                "appid": str(appid),
                "name":  catalog.get(str(appid), {}).get("name", f"App {appid}"),
                "reviews": (
                    (catalog.get(str(appid), {}).get("positive") or 0)
                    + (catalog.get(str(appid), {}).get("negative") or 0)
                ),
            }
            for appid in appids
        ]

    if not games_list:
        log.warning(f"No games found matching all tags: {tags}")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    log.info(f"[Tags: {tags_label}] Processing {len(games_list)} games")

    for i, game in enumerate(games_list, start=1):
        appid        = game["appid"]
        name         = game["name"]
        already_seen = appid in seen_appids
        seen_appids.add(appid)

        log.info(f"  [{i}/{len(games_list)}] {name} (appid: {appid})" + (" [already collected]" if already_seen else ""))

        if already_seen:
            time.sleep(game_delay)
            continue

        extraction = fetch_reviews_with_metadata(
            appid=appid,
            language="all",
            start_date=start_date,
            end_date=end_date,
            passes=passes,
        )
        reviews = extraction.reviews
        game_metadata.append({
            "appid": str(appid),
            "name": name,
            "catalog_reviews": game.get("reviews"),
            **extraction.to_metadata(),
        })

        for r in reviews:
            author = r.get("author", {})
            ts     = r.get("timestamp_created")
            date_created = (
                datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%d/%m/%Y")
                if ts else None
            )
            all_rows.append({
                "app_id":       appid,
                "app_name":     name,
                "recommendation_id": r.get("recommendationid"),
                "user_id":      author.get("steamid"),
                "country_code": None,
                "language":     r.get("language", ""),
                "review_text":  r.get("review"),
                "voted_up":     r.get("voted_up"),
                "tag":          tags_label,
                "date_created": date_created,
            })

        log.info(f"  → {len(reviews)} reviews collected")
        time.sleep(game_delay)

    if not all_rows:
        log.warning("No reviews collected. Check tags and date range.")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    df = pd.DataFrame(all_rows)

    # ------------------------------------------------------------------
    # Step 3: enrich with country_code via GetPlayerSummaries
    # ------------------------------------------------------------------
    unique_users = df["user_id"].dropna().unique().tolist()
    country_result = fetch_country_codes_with_metadata(unique_users, api_key)
    df["country_code"] = df["user_id"].map(country_result.country_map).fillna("")
    reviews_before_country_filter = len(df)

    # ------------------------------------------------------------------
    # Step 4: filter by country
    # ------------------------------------------------------------------
    if countries_upper:
        before = len(df)
        df     = df[df["country_code"].isin(countries_upper)]
        log.info(f"Filter: kept {len(df):,} / {before:,} reviews matching countries: {', '.join(countries_upper)}")

    country_metadata = country_result.to_metadata()
    country_metadata["reviews_before_filter"] = reviews_before_country_filter
    country_metadata["reviews_matching_filter"] = len(df)
    df.attrs["extraction_metadata"] = build_metadata(country_metadata)

    if df.empty:
        log.warning("No reviews left after country filter.")
        return df

    # ------------------------------------------------------------------
    # Step 5: summary
    # ------------------------------------------------------------------
    log.info(f"Done. Total rows: {len(df):,}")
    log.info("\n" + df.groupby(["tag", "country_code"]).size().to_string())

    return df


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def save_output(df: pd.DataFrame, filename: str, format_type: str = "csv") -> None:
    """Saves the DataFrame to CSV or JSON."""
    metadata = df.attrs.get("extraction_metadata")
    if df.empty:
        log.warning("Nothing to save.")
        if metadata is not None:
            metadata["output"] = {"rows": 0, "format": format_type, "file": None}
            manifest_file = save_manifest(filename, metadata)
            log.info(f"Saved metadata: {manifest_file}")
        return

    path = f"{filename}.{format_type}"
    if format_type == "json":
        df.to_json(path, orient="records", force_ascii=False, indent=2)
    else:
        df.to_csv(path, index=False, encoding="utf-8")

    log.info(f"Saved: {path} ({len(df):,} rows)")
    if metadata is not None:
        metadata["output"] = {"rows": len(df), "format": format_type, "file": path}
        manifest_file = save_manifest(filename, metadata)
        log.info(f"Saved metadata: {manifest_file}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Tag Extractor — collects Steam reviews by genre/category and country.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Build catalog first (once):
  python3 steamspy_catalog_fetcher.py

  # MVP test:
  python3 tag_extractor.py --tags Action --countries BR US \
      --start 01/12/2025 --end 31/12/2025 \
      --max-games 2 --api-key YOUR_KEY

  # Larger run:
  python3 tag_extractor.py --tags Action FPS Singleplayer \
      --countries BR US --start 01/01/2024 --end 31/12/2024 \
      --max-games 10 --api-key YOUR_KEY
        """
    )

    parser.add_argument("--tags",        nargs="+", required=True,
                        help="Genre or category names (e.g. Action FPS Singleplayer)")
    parser.add_argument("--countries",   nargs="+", default=[],
                        help="ISO country codes to keep (e.g. BR US). Omit to keep all.")
    parser.add_argument("--start",       required=True, help="Start date dd/mm/yyyy")
    parser.add_argument("--end",         required=True, help="End date dd/mm/yyyy")
    parser.add_argument("--api-key",     default=None,
                        help="Steam Web API key (or set STEAM_API_KEY env var)")
    parser.add_argument("--db",          default=DEFAULT_DB,
                        help=f"Path to local SteamSpy catalog (default: {DEFAULT_DB})")
    parser.add_argument("--appids",       nargs="+", default=None,
                        help="Specific app IDs to collect (skips catalog tag lookup)")
    parser.add_argument("--max-games",   type=int, default=10,
                        help="Max games per tag when not using --appids (default: 10)")
    parser.add_argument("--min-reviews", type=int, default=0,
                        help="Min total reviews a game must have to be included (default: 0)")
    parser.add_argument("--format",      choices=["csv", "json"], default="csv",
                        help="Output format (default: csv)")
    parser.add_argument("--output",      default=None,
                        help="Output filename without extension (auto-generated if omitted)")
    parser.add_argument("--passes",      type=int, default=1, metavar="N",
                        help="Collection passes per game merged via deduplication (default: 1). "
                             "Use 3+ to recover reviews missed by cursor drift.")
    parser.add_argument("--game-delay",  type=float, default=GAME_DELAY, metavar="S",
                        help=f"Seconds to wait between games (default: {GAME_DELAY}). "
                             "Increase to reduce session throttling when processing "
                             "multiple high-volume games.")

    args = parser.parse_args()

    api_key = args.api_key or os.environ.get("STEAM_API_KEY")
    if not api_key:
        print("Error: Steam API key required. Use --api-key or set STEAM_API_KEY env var.")
        return 1

    log_file = setup_logging()
    log.info(f"Log file: {log_file}")

    try:
        start_date = parse_date(args.start)
        end_date   = parse_date(args.end)
        if start_date > end_date:
            raise ValueError("--start must be before or equal to --end")
    except ValueError as e:
        log.error(f"Date error: {e}")
        return 1

    log.info("=" * 55)
    log.info("Steam Extractor v8.0.0")
    log.info(f"Tags     : {', '.join(args.tags)}")
    log.info(f"Countries: {', '.join(args.countries) if args.countries else 'all'}")
    log.info(f"Period   : {args.start} -> {args.end}")
    log.info(f"Max games: {args.max_games} per tag")
    log.info(f"Catalog  : {args.db}")
    log.info("=" * 55)

    df = extract_reviews_by_tags(
        tags=args.tags,
        countries=args.countries,
        start_date=start_date,
        end_date=end_date,
        api_key=api_key,
        db_path=args.db,
        max_games_per_tag=args.max_games,
        min_reviews=args.min_reviews,
        appids=args.appids,
        passes=args.passes,
        game_delay=args.game_delay,
    )

    if args.output:
        output_name = args.output
    else:
        tags_slug      = "_".join(args.tags).lower()
        countries_slug = "_".join(args.countries).lower() or "all"
        safe_start     = args.start.replace("/", "-")
        safe_end       = args.end.replace("/", "-")
        output_name    = f"reviews_{tags_slug}_{countries_slug}_{safe_start}_{safe_end}"

    save_output(df, output_name, args.format)
    return 0


if __name__ == "__main__":
    main()
