#!/usr/bin/env python3

"""
Tag Extractor - Extracts Steam reviews grouped by genre tags and country.

Builds on steam_extractor.py: uses a local Steam catalog (generated by
steamspy_catalog_fetcher.py) to discover app IDs by user tag, then
calls the Steam API to collect reviews and enriches each review with the
author's country via GetPlayerSummaries.

Output schema: app_id | app_name | user_id | country_code | language |
               review_text | voted_up | tag | date_created

Usage:
    # First, build the local catalog (once):
    python3 steamspy_catalog_fetcher.py

    # Then extract reviews:
    python3 tag_extractor.py --tags Action FPS --countries BR US \
        --start 01/01/2023 --end 31/12/2023 \
        --api-key YOUR_KEY
"""

import argparse
import json
import logging
import os
import time
from dataclasses import dataclass
from datetime import date, datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

import pandas as pd
import requests

from steam_extractor.review_store import ReviewStore, review_content_hash
from steam_extractor.reviews_fetcher import (
    fetch_reviews_with_metadata,
    parse_date,
    save_manifest,
    software_metadata,
)

log = logging.getLogger(__name__)


def setup_logging() -> str:
    """Configures logging to console and a timestamped file under ./logs/."""
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file  = log_dir / f"extraction_{timestamp}.log"

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%d/%m/%Y %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, encoding="utf-8"),
            logging.StreamHandler(),
        ],
    )
    return str(log_file)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_DB         = "steamspy_catalog.json"
DEFAULT_PROFILE_DB = "steam_profiles.sqlite"
PLAYER_SUMMARY_URL = "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/"
GAME_DELAY         = 1.5
PROFILE_DELAY      = 0.5
MAX_PROFILE_DELAY  = 5.0
BATCH_SIZE         = 100


@dataclass
class CountryFetchResult:
    country_map: dict[str, str]
    requested_users: int
    returned_profiles: int
    country_available: int
    failed_batches: int
    failed_users: int
    status_map: dict[str, str] | None = None
    cached_users: int = 0
    newly_checked_users: int = 0
    pending_users: int = 0
    rate_limit_events: int = 0
    retry_after_events: int = 0
    retry_wait_seconds: float = 0.0
    initial_request_delay: float = PROFILE_DELAY
    final_request_delay: float = PROFILE_DELAY

    def to_metadata(self) -> dict:
        statuses = self.status_map or {}
        unavailable = sum(
            status == "country_unavailable" for status in statuses.values()
        )
        classified = sum(
            status
            in {
                "country_available",
                "country_unavailable",
                "profile_unavailable",
            }
            for status in statuses.values()
        )
        attempted = classified + sum(
            status == "request_failed" for status in statuses.values()
        )
        return {
            "unique_authors": self.requested_users,
            "profiles_returned": self.returned_profiles,
            "country_available": self.country_available,
            "country_unavailable": unavailable,
            "profile_unavailable": sum(
                status == "profile_unavailable" for status in statuses.values()
            ),
            "request_failed": sum(
                status == "request_failed" for status in statuses.values()
            ),
            "failed_batches": self.failed_batches,
            "failed_users": self.failed_users,
            "cached_users": self.cached_users,
            "newly_checked_users": self.newly_checked_users,
            "pending_users": self.pending_users,
            "rate_limit_events": self.rate_limit_events,
            "retry_after_events": self.retry_after_events,
            "retry_wait_seconds": round(self.retry_wait_seconds, 2),
            "initial_request_delay": self.initial_request_delay,
            "final_request_delay": round(self.final_request_delay, 2),
            "attempted_users": attempted,
            "classified_users": classified,
            "processing_coverage_percent": (
                round(classified / self.requested_users * 100, 2)
                if self.requested_users
                else 100.0
            ),
            "country_availability_among_classified_percent": (
                round(self.country_available / classified * 100, 2)
                if classified
                else 0.0
            ),
            "complete": self.failed_batches == 0 and self.pending_users == 0,
        }


# ---------------------------------------------------------------------------
# Local catalog helpers
# ---------------------------------------------------------------------------

def load_catalog_with_metadata(db_path: str) -> tuple[dict, dict]:
    """Loads games and metadata from a local SteamSpy catalog."""
    path = Path(db_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Steam catalog not found at '{db_path}'.\n"
            f"Run first: python3 steamspy_catalog_fetcher.py"
        )

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    games = data.get("games", {})
    meta  = data.get("metadata", {})
    log.info(f"Catalog loaded: {len(games):,} games from '{db_path}' (downloaded: {meta.get('downloaded_at', 'unknown')})")
    return games, meta


def load_catalog(db_path: str) -> dict:
    """Backward-compatible helper returning only games from the catalog."""
    games, _metadata = load_catalog_with_metadata(db_path)
    return games


def get_appids_by_tags(
    tags: list[str],
    games: dict,
    min_reviews: int = 0,
) -> list[dict]:
    """
    Filters the local SteamSpy catalog by multiple user tags (AND logic)
    and minimum review count. A game must have ALL specified tags to be included.
    Results are sorted by total reviews descending (most reviewed first).

    Args:
        tags:        list of user tag names (e.g. ['FPS', 'Multiplayer'])
        games:       dict loaded from steamspy_catalog.json
        min_reviews: minimum total reviews (positive + negative, default: 0)

    Returns:
        List of dicts with keys: appid, name — sorted by review count desc.
    """
    tags_lower = [t.lower() for t in tags]
    log.info(f"Filtering for tags: {tags} (AND, min reviews: {min_reviews:,})")
    filtered = []

    for appid, info in games.items():
        game_tags = [t.lower() for t in info.get("tags", {}).keys()]
        total     = (info.get("positive") or 0) + (info.get("negative") or 0)

        if all(t in game_tags for t in tags_lower) and total >= min_reviews:
            filtered.append({
                "appid":   appid,
                "name":    info.get("name", "Unknown"),
                "reviews": total,
            })

    filtered.sort(key=lambda g: g["reviews"], reverse=True)
    log.info(f"Found {len(filtered)} games matching all tags with >= {min_reviews:,} reviews")
    return filtered


# ---------------------------------------------------------------------------
# Player profile enrichment
# ---------------------------------------------------------------------------

def fetch_country_codes_with_metadata(
    user_ids: list[str],
    api_key: str,
    *,
    store: ReviewStore | None = None,
    max_batches: int | None = None,
    max_runtime: float | None = None,
    refresh_profiles: bool = False,
) -> CountryFetchResult:
    """
    Fetches country_code for a list of Steam user IDs via GetPlayerSummaries.
    Processes up to 100 IDs per API call.

    Returns dict mapping steamid → country_code (empty string if unavailable).
    """
    user_ids = list(dict.fromkeys(str(value) for value in user_ids if value))
    cached = store.get_player_profiles(user_ids) if store else {}
    terminal_statuses = {
        "country_available",
        "country_unavailable",
        "profile_unavailable",
    }
    reusable = (
        {}
        if refresh_profiles
        else {
            steam_id: profile
            for steam_id, profile in cached.items()
            if profile["status"] in terminal_statuses
        }
    )
    country_map = {
        steam_id: profile.get("country_code") or ""
        for steam_id, profile in reusable.items()
    }
    status_map = {
        steam_id: str(profile["status"]) for steam_id, profile in reusable.items()
    }
    returned_profiles = 0
    failed_batches = 0
    failed_users = 0
    pending_ids = [steam_id for steam_id in user_ids if steam_id not in reusable]
    batches = [
        pending_ids[i:i + BATCH_SIZE]
        for i in range(0, len(pending_ids), BATCH_SIZE)
    ]
    started = time.monotonic()
    processed_users = 0
    runtime_exhausted = False
    request_delay = PROFILE_DELAY
    successful_batches = 0
    rate_limit_events = 0
    retry_after_events = 0
    retry_wait_seconds = 0.0

    def retry_after_seconds(response) -> float | None:
        value = response.headers.get("Retry-After") if response is not None else None
        if not value:
            return None
        try:
            return max(float(value), 0.0)
        except ValueError:
            try:
                retry_at = parsedate_to_datetime(value)
                if retry_at.tzinfo is None:
                    retry_at = retry_at.replace(tzinfo=timezone.utc)
                return max(
                    (retry_at - datetime.now(tz=timezone.utc)).total_seconds(),
                    0.0,
                )
            except (TypeError, ValueError, OverflowError):
                return None

    def wait_within_runtime(seconds: float) -> bool:
        """Waits for a retry without crossing the configured command deadline."""
        if max_runtime is None:
            time.sleep(seconds)
            return True
        remaining = max_runtime - (time.monotonic() - started)
        if remaining <= 0:
            return False
        time.sleep(min(seconds, remaining))
        return seconds < remaining

    log.info(
        "Player profiles: %s cached, %s pending in %s batches",
        len(reusable),
        len(pending_ids),
        len(batches),
    )

    for i, batch in enumerate(batches, start=1):
        if max_batches is not None and i > max_batches:
            break
        if max_runtime is not None and time.monotonic() - started >= max_runtime:
            break
        max_retries = 3
        batch_succeeded = False
        players: list[dict] = []
        for attempt in range(max_retries):
            if (
                max_runtime is not None
                and time.monotonic() - started >= max_runtime
            ):
                runtime_exhausted = True
                break
            try:
                r = requests.get(
                    PLAYER_SUMMARY_URL,
                    params={"key": api_key, "steamids": ",".join(batch)},
                    timeout=30
                )
                r.raise_for_status()
                players = r.json().get("response", {}).get("players", [])
                returned_profiles += len(players)
                batch_succeeded = True
                successful_batches += 1
                if successful_batches % 10 == 0 and request_delay > PROFILE_DELAY:
                    previous_delay = request_delay
                    request_delay = max(PROFILE_DELAY, request_delay * 0.9)
                    log.info(
                        "Adaptive profile delay reduced from %.2fs to %.2fs "
                        "after 10 successful batches",
                        previous_delay,
                        request_delay,
                    )
                break
            except requests.exceptions.HTTPError as e:
                status = e.response.status_code if e.response is not None else "?"
                if status == 429:
                    rate_limit_events += 1
                    successful_batches = 0
                    request_delay = min(
                        MAX_PROFILE_DELAY,
                        max(1.0, request_delay * 1.5),
                    )
                    retry_after = retry_after_seconds(e.response)
                    if retry_after is not None:
                        retry_after_events += 1
                    if attempt < max_retries - 1:
                        wait = (
                            retry_after
                            if retry_after is not None
                            else 30 * (attempt + 1)
                        )
                        retry_wait_seconds += wait
                        log.warning(
                            "Rate limited on batch %s (attempt %s/%s), waiting "
                            "%.1fs; adaptive delay now %.2fs%s",
                            i,
                            attempt + 1,
                            max_retries,
                            wait,
                            request_delay,
                            " (Retry-After)" if retry_after is not None else "",
                        )
                        if not wait_within_runtime(wait):
                            runtime_exhausted = True
                            break
                    else:
                        log.warning(
                            "Rate limited on batch %s (attempt %s/%s); no further "
                            "retry for this batch, adaptive delay now %.2fs",
                            i,
                            attempt + 1,
                            max_retries,
                            request_delay,
                        )
                else:
                    log.warning(f"HTTP {status} error on batch {i} (attempt {attempt+1}/{max_retries})")
                    if attempt < max_retries - 1 and not wait_within_runtime(
                        2 ** attempt
                    ):
                        runtime_exhausted = True
                        break
            except requests.exceptions.RequestException as e:
                wait = 2 ** attempt
                log.warning(
                    "Transport error on batch %s: %s (attempt %s/%s)",
                    i,
                    type(e).__name__,
                    attempt + 1,
                    max_retries,
                )
                if attempt < max_retries - 1 and not wait_within_runtime(wait):
                    runtime_exhausted = True
                    break
            except Exception as e:
                log.warning(f"Error on batch {i}: {type(e).__name__} (attempt {attempt+1}/{max_retries})")
                break

        if runtime_exhausted and not batch_succeeded:
            log.info(
                "Profile enrichment runtime reached before batch %s completed; "
                "the batch remains pending",
                i,
            )
            break

        if not batch_succeeded:
            failed_batches += 1
            failed_users += len(batch)
            failed_profiles = []
            for steam_id in batch:
                previous = cached.get(steam_id)
                if previous and previous["status"] in terminal_statuses:
                    country_map[steam_id] = previous.get("country_code") or ""
                    status_map[steam_id] = str(previous["status"])
                    continue
                status_map[steam_id] = "request_failed"
                failed_profiles.append(
                    {
                        "steam_id": steam_id,
                        "country_code": None,
                        "status": "request_failed",
                    }
                )
            if store:
                store.save_player_profiles(failed_profiles)
        else:
            returned = {
                str(player.get("steamid")): player
                for player in players
                if player.get("steamid")
            }
            batch_profiles = []
            for steam_id in batch:
                player = returned.get(steam_id)
                country = (
                    str(player.get("loccountrycode") or "").upper()
                    if player
                    else ""
                )
                status = (
                    "country_available"
                    if country
                    else "country_unavailable"
                    if player
                    else "profile_unavailable"
                )
                country_map[steam_id] = country
                status_map[steam_id] = status
                batch_profiles.append(
                    {
                        "steam_id": steam_id,
                        "country_code": country or None,
                        "status": status,
                    }
                )
            if store:
                store.save_player_profiles(batch_profiles)
        processed_users += len(batch)

        if i % 10 == 0:
            log.info(f"Profile batch {i}/{len(batches)} done")

        if not wait_within_runtime(request_delay):
            break

    filled = sum(1 for steam_id in user_ids if country_map.get(steam_id))
    total  = len(user_ids)
    if total:
        log.info(f"country_code found for {filled:,} / {total:,} users ({filled/total*100:.1f}%)")

    return CountryFetchResult(
        country_map=country_map,
        requested_users=len(user_ids),
        returned_profiles=returned_profiles,
        country_available=filled,
        failed_batches=failed_batches,
        failed_users=failed_users,
        status_map=status_map,
        cached_users=len(reusable),
        newly_checked_users=processed_users,
        pending_users=max(len(pending_ids) - processed_users, 0),
        rate_limit_events=rate_limit_events,
        retry_after_events=retry_after_events,
        retry_wait_seconds=retry_wait_seconds,
        initial_request_delay=PROFILE_DELAY,
        final_request_delay=request_delay,
    )


def fetch_country_codes(user_ids: list[str], api_key: str) -> dict[str, str]:
    """Backward-compatible wrapper returning only the country mapping."""
    return fetch_country_codes_with_metadata(user_ids, api_key).country_map


# ---------------------------------------------------------------------------
# Core extraction pipeline
# ---------------------------------------------------------------------------

def extract_reviews_by_tags(
    tags: list[str],
    countries: list[str],
    start_date: date,
    end_date: date,
    api_key: str,
    db_path: str = DEFAULT_DB,
    max_games_per_tag: int = 10,
    min_reviews: int = 0,
    appids: list[str] | None = None,
    passes: int = 1,
    game_delay: float = GAME_DELAY,
    review_database: str | None = None,
    allow_unverified_cache: bool = False,
    profile_database: str | None = None,
    profile_max_batches: int | None = None,
    profile_max_runtime: float | None = None,
    refresh_profiles: bool = False,
) -> pd.DataFrame:
    """
    Full pipeline:
        1. Local catalog → app IDs per tag
        2. Steam API     → reviews per app
        3. GetPlayerSummaries → country_code per user (batched)
        4. Filter known countries while retaining unresolved country records
        5. Return structured DataFrame

    Output columns:
        app_id, app_name, recommendation_id, review_version, review_content_hash,
        user_id, country_code, country_status, language, review_text, voted_up,
        tag, date_created
    """
    catalog, catalog_metadata = load_catalog_with_metadata(db_path)
    all_rows        = []
    game_metadata: list[dict] = []
    seen_appids: set[str] = set()
    countries_upper = [c.upper() for c in countries]

    def build_metadata(country_metadata: dict | None = None) -> dict:
        games_complete = bool(game_metadata) and all(
            game["complete"] for game in game_metadata
        )
        country_complete = (
            country_metadata is None or country_metadata.get("complete", False)
        )
        return {
            "schema_version": 1,
            "created_at": datetime.now(tz=timezone.utc).isoformat(),
            "software": software_metadata(),
            "query": {
                "tags": tags,
                "appids": [str(appid) for appid in appids] if appids else None,
                "countries": countries_upper,
                "language": "all",
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat(),
                "passes_requested": passes,
                "selection_mode": "explicit_appids" if appids else "tag_top_reviews",
                "max_games": max_games_per_tag,
                "min_reviews": min_reviews,
                "steam_filter": "recent",
                "offtopic_included": False,
                "review_database": review_database,
                "profile_database": profile_database,
                "profile_max_batches": profile_max_batches,
                "profile_max_runtime": profile_max_runtime,
                "refresh_profiles": refresh_profiles,
                "allow_unverified_cache": allow_unverified_cache,
            },
            "catalog": {**catalog_metadata, "path": db_path},
            "games": game_metadata,
            "country_enrichment": country_metadata,
            "dataset_complete": games_complete and country_complete,
        }

    # ------------------------------------------------------------------
    # Steps 1 & 2: discover games and collect reviews
    # ------------------------------------------------------------------
    tags_label = " & ".join(tags)

    if not appids:
        games_list = get_appids_by_tags(tags, catalog, min_reviews=min_reviews)
        games_list = games_list[:max_games_per_tag]
    else:
        games_list = []

    if not games_list and not appids:
        log.warning(f"No games found matching all tags: {tags}")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    tag = tags_label

    # Handle --appids: build games_list from explicit appids if provided
    if appids:
        games_list = [
            {
                "appid": str(appid),
                "name":  catalog.get(str(appid), {}).get("name", f"App {appid}"),
                "reviews": (
                    (catalog.get(str(appid), {}).get("positive") or 0)
                    + (catalog.get(str(appid), {}).get("negative") or 0)
                ),
            }
            for appid in appids
        ]

    if not games_list:
        log.warning(f"No games found matching all tags: {tags}")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    log.info(f"[Tags: {tags_label}] Processing {len(games_list)} games")

    for i, game in enumerate(games_list, start=1):
        appid        = game["appid"]
        name         = game["name"]
        already_seen = appid in seen_appids
        seen_appids.add(appid)

        log.info(f"  [{i}/{len(games_list)}] {name} (appid: {appid})" + (" [already collected]" if already_seen else ""))

        if already_seen:
            time.sleep(game_delay)
            continue

        reviews = None
        cached_metadata = None
        if review_database:
            with ReviewStore(review_database) as store:
                verified_cache = store.has_coverage(appid, "all", start_date, end_date)
                unverified_cache = (
                    allow_unverified_cache
                    and not verified_cache
                    and store.has_unverified_job_coverage(
                        appid, "all", start_date, end_date
                    )
                )
                if verified_cache or unverified_cache:
                    reviews = store.get_reviews(appid, start_date, end_date, language="all")
                    coverage = store.get_coverage(appid, "all", "recent")
                    cached_metadata = {
                        "complete": verified_cache,
                        "completion_reason": (
                            "local_database_coverage"
                            if verified_cache
                            else "local_database_unverified_coverage"
                        ),
                        "passes_executed": 0,
                        "unique_reviews_in_date_range": len(reviews),
                        "drift_detected": False,
                        "passes": [],
                        "source": "sqlite_cache",
                        "archive": {
                            "database": review_database,
                            "coverage": coverage,
                            "coverage_verified": verified_cache,
                        },
                    }
                    log.info(
                        f"  → using {len(reviews):,} cached reviews from '{review_database}'"
                    )
                else:
                    log.info(
                        f"  → local database has no complete coverage for this interval; "
                        f"falling back to Steam"
                    )

        if reviews is None:
            extraction = fetch_reviews_with_metadata(
                appid=appid,
                language="all",
                start_date=start_date,
                end_date=end_date,
                passes=passes,
            )
            reviews = extraction.reviews
            extraction_metadata = {**extraction.to_metadata(), "source": "steam_api"}
        else:
            extraction_metadata = cached_metadata

        game_metadata.append({
            "appid": str(appid),
            "name": name,
            "catalog_reviews": game.get("reviews"),
            **extraction_metadata,
        })

        for r in reviews:
            author = r.get("author", {})
            ts     = r.get("timestamp_created")
            date_created = (
                datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%d/%m/%Y")
                if ts else None
            )
            all_rows.append({
                "app_id":       appid,
                "app_name":     name,
                "recommendation_id": r.get("recommendationid"),
                "review_version": r.get("_archive_version", 1),
                "review_content_hash": r.get(
                    "_archive_content_hash", review_content_hash(r)
                ),
                "user_id":      author.get("steamid"),
                "country_code": None,
                "language":     r.get("language", ""),
                "review_text":  r.get("review"),
                "voted_up":     r.get("voted_up"),
                "tag":          tags_label,
                "date_created": date_created,
            })

        log.info(f"  → {len(reviews)} reviews collected")
        time.sleep(game_delay)

    if not all_rows:
        log.warning("No reviews collected. Check tags and date range.")
        df = pd.DataFrame()
        df.attrs["extraction_metadata"] = build_metadata()
        return df

    df = pd.DataFrame(all_rows)

    # ------------------------------------------------------------------
    # Step 3: enrich with country_code via GetPlayerSummaries
    # ------------------------------------------------------------------
    unique_users = df["user_id"].dropna().unique().tolist()
    profile_store_path = profile_database or review_database
    if profile_store_path:
        with ReviewStore(profile_store_path) as profile_store:
            country_result = fetch_country_codes_with_metadata(
                unique_users,
                api_key,
                store=profile_store,
                max_batches=profile_max_batches,
                max_runtime=profile_max_runtime,
                refresh_profiles=refresh_profiles,
            )
    else:
        country_result = fetch_country_codes_with_metadata(
            unique_users,
            api_key,
            max_batches=profile_max_batches,
            max_runtime=profile_max_runtime,
            refresh_profiles=refresh_profiles,
        )
    df["country_code"] = df["user_id"].map(country_result.country_map).fillna("")
    status_map = country_result.status_map or {
        steam_id: (
            "country_available" if country else "country_unavailable"
        )
        for steam_id, country in country_result.country_map.items()
    }
    df["country_status"] = (
        df["user_id"].map(status_map).fillna("not_checked")
    )
    reviews_before_country_filter = len(df)
    available_country = df["country_status"] == "country_available"

    def coverage_by(column: str) -> dict[str, dict]:
        summary = {}
        for value, group in df.groupby(column, dropna=False):
            total = len(group)
            statuses = group["country_status"]
            available = int((statuses == "country_available").sum())
            unavailable = int((statuses == "country_unavailable").sum())
            profile_unavailable = int((statuses == "profile_unavailable").sum())
            request_failed = int((statuses == "request_failed").sum())
            not_checked = int((statuses == "not_checked").sum())
            classified = available + unavailable + profile_unavailable
            attempted = classified + request_failed
            summary[str(value or "unknown")] = {
                "reviews_total": total,
                "attempted_reviews": attempted,
                "classified_reviews": classified,
                "country_available_reviews": available,
                "country_unavailable_reviews": unavailable,
                "profile_unavailable_reviews": profile_unavailable,
                "request_failed_reviews": request_failed,
                "not_checked_reviews": not_checked,
                "processing_coverage_percent": round(
                    classified / total * 100, 2
                ),
                "country_availability_among_classified_percent": (
                    round(available / classified * 100, 2)
                    if classified
                    else 0.0
                ),
            }
        return summary

    review_status_counts = {
        str(status): int(count)
        for status, count in df["country_status"].value_counts().items()
    }
    author_status_counts = {
        str(status): int(count)
        for status, count in pd.Series(
            unique_users, dtype="object"
        ).map(status_map).fillna("not_checked").value_counts().items()
    }
    country_distribution = {
        str(country): int(count)
        for country, count in df.loc[
            available_country, "country_code"
        ].value_counts().items()
    }
    df["_review_year"] = df["date_created"].str[-4:].fillna("unknown")
    language_coverage = coverage_by("language")
    year_coverage = coverage_by("_review_year")
    df.drop(columns=["_review_year"], inplace=True)

    # ------------------------------------------------------------------
    # Step 4: filter by country
    # ------------------------------------------------------------------
    if countries_upper:
        before = len(df)
        country_matches = df["country_code"].isin(countries_upper)
        unresolved = df["country_status"] != "country_available"
        matched_reviews = int(country_matches.sum())
        unresolved_reviews = int((~country_matches & unresolved).sum())
        df = df[country_matches | unresolved]
        log.info(
            "Filter: retained %s/%s reviews (%s matching %s; %s with unavailable "
            "or pending country)",
            len(df),
            before,
            matched_reviews,
            ", ".join(countries_upper),
            unresolved_reviews,
        )
    else:
        matched_reviews = len(df)
        unresolved_reviews = int(
            (df["country_status"] != "country_available").sum()
        )

    country_metadata = country_result.to_metadata()
    country_metadata["reviews_before_filter"] = reviews_before_country_filter
    country_metadata["author_status_counts"] = author_status_counts
    country_metadata["review_status_counts"] = review_status_counts
    country_metadata["known_country_distribution_reviews"] = country_distribution
    country_metadata["coverage_by_language"] = language_coverage
    country_metadata["coverage_by_year"] = year_coverage
    country_metadata["reviews_matching_filter"] = matched_reviews
    country_metadata["reviews_unresolved_retained"] = unresolved_reviews
    country_metadata["reviews_after_filter"] = len(df)
    df.attrs["extraction_metadata"] = build_metadata(country_metadata)

    if df.empty:
        log.warning("No reviews left after country filter.")
        return df

    # ------------------------------------------------------------------
    # Step 5: summary
    # ------------------------------------------------------------------
    log.info(f"Done. Total rows: {len(df):,}")
    log.info("\n" + df.groupby(["tag", "country_code"]).size().to_string())

    return df


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def save_output(df: pd.DataFrame, filename: str, format_type: str = "csv") -> None:
    """Saves the DataFrame to CSV or JSON."""
    metadata = df.attrs.get("extraction_metadata")
    if df.empty:
        log.warning("Nothing to save.")
        if metadata is not None:
            metadata["output"] = {"rows": 0, "format": format_type, "file": None}
            manifest_file = save_manifest(filename, metadata)
            log.info(f"Saved metadata: {manifest_file}")
        return

    path = f"{filename}.{format_type}"
    if format_type == "json":
        df.to_json(path, orient="records", force_ascii=False, indent=2)
    else:
        df.to_csv(path, index=False, encoding="utf-8")

    log.info(f"Saved: {path} ({len(df):,} rows)")
    if metadata is not None:
        metadata["output"] = {"rows": len(df), "format": format_type, "file": path}
        manifest_file = save_manifest(filename, metadata)
        log.info(f"Saved metadata: {manifest_file}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def positive_float(value: str) -> float:
    parsed = float(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def main():
    parser = argparse.ArgumentParser(
        description="Tag Extractor — collects Steam reviews by genre/category and country.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Build catalog first (once):
  python3 steamspy_catalog_fetcher.py

  # MVP test:
  python3 tag_extractor.py --tags Action --countries BR US \
      --start 01/12/2025 --end 31/12/2025 \
      --max-games 2 --api-key YOUR_KEY

  # Larger run:
  python3 tag_extractor.py --tags Action FPS Singleplayer \
      --countries BR US --start 01/01/2024 --end 31/12/2024 \
      --max-games 10 --api-key YOUR_KEY
        """
    )

    parser.add_argument("--tags",        nargs="+", required=True,
                        help="Genre or category names (e.g. Action FPS Singleplayer)")
    parser.add_argument("--countries",   nargs="+", default=[],
                        help="ISO country codes to keep (e.g. BR US). Omit to keep all.")
    parser.add_argument("--start",       required=True, help="Start date dd/mm/yyyy")
    parser.add_argument("--end",         required=True, help="End date dd/mm/yyyy")
    parser.add_argument("--api-key",     default=None,
                        help="Steam Web API key (or set STEAM_API_KEY env var)")
    parser.add_argument("--db",          default=DEFAULT_DB,
                        help=f"Path to local SteamSpy catalog (default: {DEFAULT_DB})")
    parser.add_argument("--review-db",   default=None,
                        help="Optional SQLite review archive; reuse it when coverage is complete")
    parser.add_argument(
        "--profile-db",
        default=None,
        help="SQLite profile cache (default: --review-db, or steam_profiles.sqlite)",
    )
    parser.add_argument(
        "--profile-max-batches",
        type=positive_int,
        default=None,
        metavar="N",
        help="Pause profile enrichment after N API batches; completed batches are cached",
    )
    parser.add_argument(
        "--profile-max-runtime",
        type=positive_float,
        default=None,
        metavar="SECONDS",
        help="Pause profile enrichment after this wall-clock duration",
    )
    parser.add_argument(
        "--refresh-profiles",
        action="store_true",
        help="Query terminal cached profiles again instead of reusing them",
    )
    parser.add_argument("--allow-unverified-cache", action="store_true",
                        help="Allow resumed SQLite coverage that could not be fully verified; "
                             "the manifest will mark the dataset incomplete")
    parser.add_argument("--appids",       nargs="+", default=None,
                        help="Specific app IDs to collect (skips catalog tag lookup)")
    parser.add_argument("--max-games",   type=int, default=10,
                        help="Max games per tag when not using --appids (default: 10)")
    parser.add_argument("--min-reviews", type=int, default=0,
                        help="Min total reviews a game must have to be included (default: 0)")
    parser.add_argument("--format",      choices=["csv", "json"], default="csv",
                        help="Output format (default: csv)")
    parser.add_argument("--output",      default=None,
                        help="Output filename without extension (auto-generated if omitted)")
    parser.add_argument("--passes",      type=int, default=1, metavar="N",
                        help="Collection passes per game merged via deduplication (default: 1). "
                             "Use 3+ to recover reviews missed by cursor drift.")
    parser.add_argument("--game-delay",  type=float, default=GAME_DELAY, metavar="S",
                        help=f"Seconds to wait between games (default: {GAME_DELAY}). "
                             "Increase to reduce session throttling when processing "
                             "multiple high-volume games.")

    args = parser.parse_args()

    api_key = args.api_key or os.environ.get("STEAM_API_KEY")
    if not api_key:
        print("Error: Steam API key required. Use --api-key or set STEAM_API_KEY env var.")
        return 1

    log_file = setup_logging()
    log.info(f"Log file: {log_file}")

    try:
        start_date = parse_date(args.start)
        end_date   = parse_date(args.end)
        if start_date > end_date:
            raise ValueError("--start must be before or equal to --end")
    except ValueError as e:
        log.error(f"Date error: {e}")
        return 1

    log.info("=" * 55)
    log.info("Steam Extractor v8.0.0")
    log.info(f"Tags     : {', '.join(args.tags)}")
    log.info(f"Countries: {', '.join(args.countries) if args.countries else 'all'}")
    log.info(f"Period   : {args.start} -> {args.end}")
    log.info(f"Max games: {args.max_games} per tag")
    log.info(f"Catalog  : {args.db}")
    log.info("=" * 55)

    df = extract_reviews_by_tags(
        tags=args.tags,
        countries=args.countries,
        start_date=start_date,
        end_date=end_date,
        api_key=api_key,
        db_path=args.db,
        max_games_per_tag=args.max_games,
        min_reviews=args.min_reviews,
        appids=args.appids,
        passes=args.passes,
        game_delay=args.game_delay,
        review_database=args.review_db,
        allow_unverified_cache=args.allow_unverified_cache,
        profile_database=args.profile_db or args.review_db or DEFAULT_PROFILE_DB,
        profile_max_batches=args.profile_max_batches,
        profile_max_runtime=args.profile_max_runtime,
        refresh_profiles=args.refresh_profiles,
    )

    if args.output:
        output_name = args.output
    else:
        tags_slug      = "_".join(args.tags).lower()
        countries_slug = "_".join(args.countries).lower() or "all"
        safe_start     = args.start.replace("/", "-")
        safe_end       = args.end.replace("/", "-")
        output_name    = f"reviews_{tags_slug}_{countries_slug}_{safe_start}_{safe_end}"

    save_output(df, output_name, args.format)
    return 0


if __name__ == "__main__":
    main()
